%%{init: {
  'theme': 'neutral',
  'themeVariables': {
    'background': '#ffffff',
    'fontSize': '24px',
    'titleColor': '#222222'
  }
}}%%
graph TD
    subgraph Triggers ["Eventos de disparo (GitHub Actions)"]
        T1["Push a develop"]
        T2["Push a main"]
    end

    subgraph CI ["CI - Calidad y seguridad"]
        B1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>backend-ci</div>"]
        F1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>frontend-ci</div>"]
        B2["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>pytest-backend-tests</div>"]
        L1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>locust-performance-tests</div>"]
        E1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>playwright-e2e-tests</div>"]
        F2["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>vitest-component-tests</div>"]
    end

    subgraph SQ ["SonarQube - Calidad del código"]
        S1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>sonarqube</div>"]
    end

    subgraph CD ["CD - Despliegue a producción"]
        D1["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>deploy</div>"]
        D2["<div style='background:#333; color:#fff; padding:6px 14px; border-radius:4px;'>vercel</div>"]
    end

    T1 --> B1
    T1 --> F1
    T2 --> SQ
    T2 --> D1
    T2 -.-> | Integración nativa de Github| D2 

    B1 --> B2
    B2 --> L1
    B2 --> E1
    F1 --> E1
    F1 --> F2

    style S1 stroke:#55ccaa,stroke-width:2px
    style D1 stroke:#007976,stroke-width:2px
    style D2 stroke:#007976,stroke-width:2px
    style B1 stroke:#a946ab,stroke-width:2px
    style B2 stroke:#a946ab,stroke-width:2px
    style F1 stroke:#a946ab,stroke-width:2px
    style F2 stroke:#a946ab,stroke-width:2px
    style E1 stroke:#a946ab,stroke-width:2px
    style L1 stroke:#a946ab,stroke-width:2px
    style T2 fill:#55ccaa,stroke:#2b6854,color:#fff,stroke-width:1px
    style T1 fill:#a946ab,stroke:#7d386f,color:#fff,stroke-width:1px

    linkStyle 4 stroke-width:1px,stroke-dasharray:10 10

    %% npx -p @mermaid-js/mermaid-cli mmdc -i thesis/figures/ci_cd_simplificado.mmd -o thesis/figures/ci_cd_simplificado.png -s 2 -w 2400 -H 1600 -b white